//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHalls
    {
        public int ID { get; set; }
        public string CodeHall { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<double> PercentTax { get; set; }
        public Nullable<decimal> CostRef_Halls { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> LunarDate { get; set; }
        public Nullable<int> BookingStatus { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> TableOrPerson { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public string Location { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsAllDayEvent { get; set; }
        public Nullable<bool> Color { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public string AdditionalColumn1 { get; set; }
        public int IDBookingH { get; set; }
        public Nullable<int> IndexSubPayment { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
    }
}
