//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRs_BookingHs
    {
        public int ID { get; set; }
        public Nullable<int> IDBookingR { get; set; }
        public Nullable<int> IDBookingH { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Disable { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
    }
}
