//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRooms_Services
    {
        public int ID { get; set; }
        public string Info { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Disable { get; set; }
        public int IDBookingRoom { get; set; }
        public int IDService { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> PercentTax { get; set; }
        public Nullable<decimal> CostRef_Services { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> IndexSubPayment { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
    }
}
