//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts_Allowances
    {
        public int ID { get; set; }
        public Nullable<decimal> RealSalaryPlus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Disable { get; set; }
        public int IDAllowance { get; set; }
        public int IDContract { get; set; }
    }
}
