//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Identifier1 { get; set; }
        public string Identifier2 { get; set; }
        public string Identifier3 { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Info { get; set; }
        public string Note { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Disable { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Citizen { get; set; }
        public Nullable<System.DateTime> Identifier1CreatedDate { get; set; }
        public Nullable<System.DateTime> Identifier2CreatedDate { get; set; }
        public Nullable<System.DateTime> Identifier3CreatedDate { get; set; }
        public string PlaceOfIssue1 { get; set; }
        public string PlaceOfIssue2 { get; set; }
        public string PlaceOfIssue3 { get; set; }
    }
}
