//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designations
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SignedBy { get; set; }
        public string DesignationsCode { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Note { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<int> FileType { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
