//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halls
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Sku { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> NumTableStandard { get; set; }
        public Nullable<int> NumTableMax { get; set; }
        public string Intro { get; set; }
        public string Info { get; set; }
        public Nullable<decimal> CostRef { get; set; }
        public string CostUnit { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Disable { get; set; }
        public Nullable<int> IDLang { get; set; }
    }
}
