//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> IDBookingR { get; set; }
        public Nullable<int> IDBookingRoom { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public string NameCustomer { get; set; }
        public Nullable<int> IDSystemUser { get; set; }
        public string NameSystemUser { get; set; }
        public Nullable<int> IDCustomerGroup { get; set; }
        public string NameCustomerGroup { get; set; }
        public Nullable<int> IDCompany { get; set; }
        public string NameCompany { get; set; }
        public Nullable<int> IDService { get; set; }
        public string NameService { get; set; }
        public string CodeRoom { get; set; }
        public string Sku { get; set; }
        public Nullable<System.DateTime> CreatedDate_BookingR { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public Nullable<int> BookingType { get; set; }
        public Nullable<int> PayMenthod { get; set; }
        public Nullable<int> StatusPay { get; set; }
        public Nullable<decimal> BookingMoney { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> Status_BookingR { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> Cost_BookingRoom { get; set; }
        public Nullable<double> PercentTax_BookingRoom { get; set; }
        public Nullable<decimal> CostRef_Rooms { get; set; }
        public Nullable<System.DateTime> CheckInActual { get; set; }
        public Nullable<System.DateTime> CheckOutActual { get; set; }
        public Nullable<int> Status_BookingRoom { get; set; }
        public Nullable<decimal> TimeInUse { get; set; }
        public Nullable<decimal> CostTotal_BookingRoom { get; set; }
        public Nullable<decimal> Cost_Services { get; set; }
        public Nullable<System.DateTime> DateUseServices { get; set; }
        public Nullable<double> PercentTax_Services { get; set; }
        public Nullable<decimal> CostRef_Services { get; set; }
        public Nullable<double> Quantity_Services { get; set; }
        public Nullable<int> Status_Services { get; set; }
        public Nullable<decimal> CostTotal_Services { get; set; }
        public Nullable<int> IndexSubRooms { get; set; }
        public Nullable<int> IndexSubServices { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
