//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsers_Divisions
    {
        public int ID { get; set; }
        public System.DateTime AvaiableDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IDSystemUser { get; set; }
        public int IDDivision { get; set; }
        public int Status { get; set; }
        public bool Disable { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    }
}
