//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsers_Certificates
    {
        public int ID { get; set; }
        public string Level { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Organization { get; set; }
        public int IDCertificate { get; set; }
        public int IDSystemUser { get; set; }
        public string TrainingType { get; set; }
    }
}
