//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserExts1
    {
        public int ID { get; set; }
        public string BirthPlace { get; set; }
        public string Hometown { get; set; }
        public string Address { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> YearJob { get; set; }
        public Nullable<System.DateTime> YearDepartment { get; set; }
        public Nullable<System.DateTime> YearPayroll { get; set; }
        public Nullable<System.DateTime> YearUnemploymentInsurance { get; set; }
        public string DifferenceContact { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Disable { get; set; }
        public Nullable<int> IDSystemUser { get; set; }
        public string Recruitment { get; set; }
        public string PermanentResidence { get; set; }
        public Nullable<System.DateTime> CommunistPartyDate { get; set; }
        public Nullable<System.DateTime> YouthUnionDate { get; set; }
        public Nullable<System.DateTime> EnlistmentDate { get; set; }
        public Nullable<System.DateTime> DemobilizedDate { get; set; }
        public Nullable<bool> MartyrsFamily { get; set; }
        public Nullable<bool> WoundedFamily { get; set; }
        public Nullable<bool> LaborFamily { get; set; }
        public string HightestAppellation { get; set; }
    }
}
