//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSalaries
    {
        public int ID { get; set; }
        public Nullable<int> IDGroupTableSalary { get; set; }
        public string Name { get; set; }
        public string Sku { get; set; }
        public Nullable<int> NumCoefficents { get; set; }
        public Nullable<double> Coe1 { get; set; }
        public Nullable<int> Jump1 { get; set; }
        public Nullable<double> Coe2 { get; set; }
        public Nullable<int> Jump2 { get; set; }
        public Nullable<double> Coe3 { get; set; }
        public Nullable<int> Jump3 { get; set; }
        public Nullable<double> Coe4 { get; set; }
        public Nullable<int> Jump4 { get; set; }
        public Nullable<double> Coe5 { get; set; }
        public Nullable<int> Jump5 { get; set; }
        public Nullable<double> Coe6 { get; set; }
        public Nullable<int> Jump6 { get; set; }
        public Nullable<double> Coe7 { get; set; }
        public Nullable<int> Jump7 { get; set; }
        public Nullable<double> Coe8 { get; set; }
        public Nullable<int> Jump8 { get; set; }
        public Nullable<double> Coe9 { get; set; }
        public Nullable<int> Jump9 { get; set; }
        public Nullable<double> Coe10 { get; set; }
        public Nullable<int> Jump10 { get; set; }
        public Nullable<double> Coe11 { get; set; }
        public Nullable<int> Jump11 { get; set; }
        public Nullable<double> Coe12 { get; set; }
        public Nullable<int> Jump12 { get; set; }
        public Nullable<double> Coe13 { get; set; }
        public Nullable<int> Jump13 { get; set; }
        public Nullable<double> Coe14 { get; set; }
        public Nullable<int> Jump14 { get; set; }
        public Nullable<double> Coe15 { get; set; }
        public Nullable<int> Jump15 { get; set; }
        public Nullable<double> Coe16 { get; set; }
        public Nullable<int> Jump16 { get; set; }
    }
}
