//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__SearchCustomer__Companies_CustomerGroups_Customers
    {
        public int Companies_ID { get; set; }
        public string Companies_Name { get; set; }
        public Nullable<int> Companies_Type { get; set; }
        public int CustomerGroups_ID { get; set; }
        public string CustomerGroups_Name { get; set; }
        public Nullable<int> CustomerGroups_Type { get; set; }
        public int Customers_ID { get; set; }
        public string Customers_Name { get; set; }
        public string Customers_Identifier1 { get; set; }
        public string Customers_Identifier2 { get; set; }
        public string Customers_Identifier3 { get; set; }
        public string Customers_Nationality { get; set; }
        public Nullable<System.DateTime> Customers_Birthday { get; set; }
        public string Customers_Tel { get; set; }
        public string Customers_Address { get; set; }
        public string Customers_Email { get; set; }
        public Nullable<int> Customers_Status { get; set; }
        public Nullable<int> Customers_Type { get; set; }
        public Nullable<bool> Customers_Disable { get; set; }
        public string Customers_Gender { get; set; }
        public Nullable<int> Customers_Citizen { get; set; }
    }
}
