//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__SystemUsersInfo__SystemUsers_Divisions
    {
        public int SystemUsers_ID { get; set; }
        public int SystemUsers_Divisions_ID { get; set; }
        public int Divisions_ID { get; set; }
        public string Divisions_Name { get; set; }
        public Nullable<int> Divisions_Type { get; set; }
        public Nullable<int> Divisions_Status { get; set; }
        public Nullable<bool> Divisions_Disable { get; set; }
        public Nullable<int> SystemUsers_UserGroup { get; set; }
        public string SystemUsers_Email { get; set; }
        public string SystemUsers_Name { get; set; }
        public string SystemUsers_Username { get; set; }
        public Nullable<System.DateTime> SystemUsers_Birthday { get; set; }
        public string SystemUsers_Identifier1 { get; set; }
        public string SystemUsers_Identifier2 { get; set; }
        public string SystemUsers_Identifier3 { get; set; }
        public byte[] SystemUsers_Image { get; set; }
        public Nullable<int> SystemUsers_Type { get; set; }
        public Nullable<int> SystemUsers_Status { get; set; }
        public System.DateTime SystemUsers_Divisions_AvaiableDate { get; set; }
        public System.DateTime SystemUsers_Divisions_CreatedDate { get; set; }
        public int SystemUsers_Divisions_Status { get; set; }
        public bool SystemUsers_Divisions_Disable { get; set; }
        public int SystemUsers_Divisions_Type { get; set; }
        public Nullable<int> SystemUserExts_ID { get; set; }
        public string SystemUserExts_BirthPlace { get; set; }
        public string SystemUserExts_Hometown { get; set; }
        public string SystemUserExts_Address { get; set; }
        public string SystemUserExts_InsuranceNumber { get; set; }
        public Nullable<System.DateTime> SystemUserExts_YearJob { get; set; }
        public Nullable<System.DateTime> SystemUserExts_YearPayroll { get; set; }
        public Nullable<System.DateTime> SystemUserExts_YearUnemploymentInsurance { get; set; }
        public string SystemUserExts_DifferenceContact { get; set; }
        public Nullable<System.DateTime> SystemUsers_Divisions_ExpireDate { get; set; }
        public Nullable<int> SystemUsers_Gender { get; set; }
        public Nullable<bool> SystemUsers_Disable { get; set; }
        public Nullable<System.DateTime> SystemUsers_Identifier1CreatedDate { get; set; }
        public Nullable<System.DateTime> SystemUsers_Identifier2CreatedDate { get; set; }
        public Nullable<System.DateTime> SystemUsers_Identifier3CreatedDate { get; set; }
        public string SystemUsers_PlaceOfIssue1 { get; set; }
        public string SystemUsers_PlaceOfIssue2 { get; set; }
        public string SystemUsers_PlaceOfIssue3 { get; set; }
        public string SystemUsers_Phone { get; set; }
    }
}
