//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__PaymentInfo__BookingRs_BookingRooms_Customers
    {
        public int BookingRs_ID { get; set; }
        public int BookingRooms_ID { get; set; }
        public Nullable<int> CustomerGroups_ID { get; set; }
        public Nullable<int> Customers_ID { get; set; }
        public Nullable<int> CustomerGroups_IDCompany { get; set; }
        public string Rooms_Sku { get; set; }
        public string BookingRooms_CodeRoom { get; set; }
        public Nullable<decimal> BookingRooms_Cost { get; set; }
        public Nullable<double> BookingRooms_PercentTax { get; set; }
        public System.DateTime BookingRooms_CheckInPlan { get; set; }
        public System.DateTime BookingRooms_CheckInActual { get; set; }
        public System.DateTime BookingRooms_CheckOutPlan { get; set; }
        public System.DateTime BookingRooms_CheckOutActual { get; set; }
        public Nullable<int> BookingRooms_BookingStatus { get; set; }
        public Nullable<int> BookingRooms_Status { get; set; }
        public string Customers_Name { get; set; }
        public string Customers_Identifier1 { get; set; }
        public string Customers_Identifier2 { get; set; }
        public string Customers_Identifier3 { get; set; }
        public string Customers_Nationality { get; set; }
        public Nullable<System.DateTime> BookingRs_CreatedDate { get; set; }
        public Nullable<int> BookingRs_CustomerType { get; set; }
        public Nullable<int> BookingRs_BookingType { get; set; }
        public Nullable<int> BookingRs_PayMenthod { get; set; }
        public Nullable<int> BookingRs_StatusPay { get; set; }
        public Nullable<decimal> BookingRs_BookingMonye { get; set; }
        public Nullable<int> BookingRs_Status { get; set; }
        public Nullable<int> BookingRs_Type { get; set; }
        public int BookingRs_Level { get; set; }
        public string BookingRs_Subject { get; set; }
        public Nullable<bool> BookingRs_Disable { get; set; }
        public string CustomerGroups_Name { get; set; }
        public Nullable<int> CustomerGroups_Type { get; set; }
    }
}
