//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__ContractsInfo__SystemUsers_Contracts_Allowances
    {
        public int Allowances_ID { get; set; }
        public Nullable<System.DateTime> Allowances_CreateDate { get; set; }
        public Nullable<int> Allowances_ContractType { get; set; }
        public Nullable<decimal> Allowances_SalaryPlus { get; set; }
        public Nullable<int> Allowances_Type { get; set; }
        public Nullable<int> Allowances_Status { get; set; }
        public Nullable<bool> Allowances_Disable { get; set; }
        public int Contracts_ID { get; set; }
        public Nullable<System.DateTime> Contracts_CreatedDate { get; set; }
        public Nullable<System.DateTime> Contracts_ContractDate { get; set; }
        public string Contracts_NumberContract { get; set; }
        public string Contracts_NumberTemplateContact { get; set; }
        public int Contracts_IDSystemUser { get; set; }
        public string Contracts_Company { get; set; }
        public string Contracts_StatutoryRepresent { get; set; }
        public Nullable<int> Contracts_StatutoryRepresentGender { get; set; }
        public string Contracts_StatutoryRepresentIdentifier { get; set; }
        public Nullable<int> Contracts_ContractType { get; set; }
        public Nullable<System.DateTime> Contracts_FromDate { get; set; }
        public Nullable<System.DateTime> Contracts_ToDate { get; set; }
        public Nullable<int> Contracts_SkuTableSalary { get; set; }
        public Nullable<double> Contracts_Coefficent { get; set; }
        public Nullable<decimal> Contracts_SalaryNet { get; set; }
        public Nullable<decimal> Contracts_SalaryCross { get; set; }
        public Nullable<int> Contracts_Type { get; set; }
        public Nullable<int> Contracts_Status { get; set; }
        public Nullable<bool> Contracts_Disable { get; set; }
        public int Contracts_Allowances_ID { get; set; }
        public Nullable<decimal> Contracts_Allowances_RealSalaryPlus { get; set; }
        public System.DateTime Contracts_Allowances_CreatedDate { get; set; }
        public Nullable<System.DateTime> Contracts_Allowances_ApplyDate { get; set; }
        public Nullable<int> Contracts_Allowances_Type { get; set; }
        public Nullable<int> Contracts_Allowances_Status { get; set; }
        public Nullable<bool> Contracts_Allowances_Disable { get; set; }
        public int Contracts_Allowances_IDAllowance { get; set; }
        public int Contracts_Allowances_IDContract { get; set; }
        public Nullable<int> SystemUsers_UserGroup { get; set; }
        public int SystemUsers_ID { get; set; }
        public string SystemUsers_Username { get; set; }
        public string SystemUsers_Name { get; set; }
        public byte[] SystemUsers_Image { get; set; }
        public Nullable<int> SystemUsers_Status { get; set; }
        public Nullable<int> SystemUsers_Type { get; set; }
        public Nullable<bool> SystemUsers_Disable { get; set; }
        public Nullable<System.DateTime> SystemUsers_Identifier1CreatedDate { get; set; }
        public Nullable<System.DateTime> SystemUsers_Identifier2CreatedDate { get; set; }
        public Nullable<System.DateTime> SystemUsers_Identifier3CreatedDate { get; set; }
        public string SystemUsers_Identifier1 { get; set; }
        public string SystemUsers_Identifier2 { get; set; }
        public string SystemUsers_Identifier3 { get; set; }
        public Nullable<System.DateTime> SystemUsers_Birthday { get; set; }
        public Nullable<int> SystemUsers_Gender { get; set; }
        public string SystemUsers_PlaceOfIssue1 { get; set; }
        public string SystemUsers_PlaceOfIssue2 { get; set; }
        public string SystemUsers_PlaceOfIssue3 { get; set; }
        public string SystemUsers_Email { get; set; }
    }
}
