//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__BookingRInfo__BookingRooms_Rooms_SystemUsers_Customers_CustomerGroups
    {
        public Nullable<int> BookingRs_CustomerType { get; set; }
        public Nullable<System.DateTime> BookingRs_CreatedDate { get; set; }
        public Nullable<int> BookingRs_BookingType { get; set; }
        public Nullable<int> BookingRs_Status { get; set; }
        public Nullable<int> BookingRs_Type { get; set; }
        public Nullable<bool> BookingRs_Disable { get; set; }
        public int BookingRs_Level { get; set; }
        public string BookingRs_Subject { get; set; }
        public System.DateTime BookingRooms_CheckInPlan { get; set; }
        public System.DateTime BookingRooms_CheckInActual { get; set; }
        public System.DateTime BookingRooms_CheckOutPlan { get; set; }
        public System.DateTime BookingRooms_CheckOutActual { get; set; }
        public Nullable<int> BookingRooms_Status { get; set; }
        public string CustomerGroups_Name { get; set; }
        public Nullable<int> CustomerGroups_Type { get; set; }
        public Nullable<int> CustomerGroups_Status { get; set; }
        public Nullable<bool> CustomerGroups_Disable { get; set; }
        public string Customers_Name { get; set; }
        public string Customers_Identifier2 { get; set; }
        public string Customers_Identifier1 { get; set; }
        public string Customers_Identifier3 { get; set; }
        public string Customers_Nationality { get; set; }
        public Nullable<System.DateTime> Customers_Birthday { get; set; }
        public string Customers_Email { get; set; }
        public string Customers_Address { get; set; }
        public Nullable<int> Customers_Status { get; set; }
        public Nullable<int> Customers_Type { get; set; }
        public Nullable<bool> Customers_Disable { get; set; }
        public string Customers_Gender { get; set; }
        public Nullable<int> Customers_Citizen { get; set; }
        public string Rooms_Sku { get; set; }
        public Nullable<int> Rooms_Bed1 { get; set; }
        public Nullable<int> Rooms_Bed2 { get; set; }
        public Nullable<int> Rooms_Type { get; set; }
        public int Rooms_Status { get; set; }
        public Nullable<bool> Rooms_Disable { get; set; }
        public string Rooms_Code { get; set; }
        public Nullable<int> BookingRs_PayMethod { get; set; }
        public Nullable<int> BookingRs_StatusPay { get; set; }
        public Nullable<decimal> BookingRs_BookingMoney { get; set; }
        public int BookingRooms_ID { get; set; }
        public int BookingRs_ID { get; set; }
        public int CustomerGroups_ID { get; set; }
        public int Customers_ID { get; set; }
        public int Rooms_ID { get; set; }
        public int SystemUsers_ID { get; set; }
        public string SystemUsers_Username { get; set; }
        public string SystemUsers_Name { get; set; }
        public string SystemUsers_Email { get; set; }
        public Nullable<System.DateTime> SystemUsers_Birthday { get; set; }
        public string SystemUsers_Identifier1 { get; set; }
        public string SystemUsers_Identifier2 { get; set; }
        public string SystemUsers_Identifier3 { get; set; }
        public Nullable<int> SystemUsers_Gender { get; set; }
        public Nullable<int> SystemUsers_Type { get; set; }
        public Nullable<int> SystemUsers_Status { get; set; }
        public Nullable<bool> SystemUsers_Disable { get; set; }
        public int BookingRooms_IDBookingR { get; set; }
        public int CustomerGroups_IDCompany { get; set; }
        public Nullable<int> BookingRooms_Type { get; set; }
        public Nullable<decimal> BookingRooms_AddTimeStart { get; set; }
        public Nullable<decimal> BookingRooms_AddTimeEnd { get; set; }
    }
}
