//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__BookingRoomInfo__BookingRs_BookingRooms_Rooms
    {
        public Nullable<System.DateTime> BookingRs_CreatedDate { get; set; }
        public Nullable<int> BookingRs_CustomerType { get; set; }
        public int BookingRs_IDCustomer { get; set; }
        public int BookingRs_IDCustomerGroup { get; set; }
        public string Rooms_Sku { get; set; }
        public Nullable<decimal> BookingRs_BookingRoomMoney { get; set; }
        public string BookingRs_Subject { get; set; }
        public System.DateTime BookingRooms_CheckInPlan { get; set; }
        public System.DateTime BookingRooms_CheckOutPlan { get; set; }
    }
}
