//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw__BookingRooms_ServicesInfo__BookingRooms_BookingRoomsServices_Services_ServiceGroups
    {
        public int BookingRooms_IDBookingR { get; set; }
        public int BookingRooms_Services_IDBookingRoom { get; set; }
        public int ServiceGroups_ID { get; set; }
        public int Services_ID { get; set; }
        public int BookingRooms_Services_ID { get; set; }
        public string Services_Name { get; set; }
        public Nullable<decimal> Services_CostRef { get; set; }
        public string Services_Unit { get; set; }
        public Nullable<int> Services_Status { get; set; }
        public Nullable<int> Services_Type { get; set; }
        public Nullable<bool> Services_Disable { get; set; }
        public string ServiceGroups_Name { get; set; }
        public Nullable<int> ServiceGroups_Type { get; set; }
        public Nullable<bool> ServiceGroups_Disable { get; set; }
        public string BookingRooms_Services_Info { get; set; }
        public Nullable<int> BookingRooms_Services_Type { get; set; }
        public Nullable<int> BookingRooms_Services_Status { get; set; }
        public Nullable<bool> BookingRooms_Services_Disable { get; set; }
        public Nullable<decimal> BookingRooms_Services_Cost { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_Date { get; set; }
        public Nullable<double> BookingRooms_Services_PercentTax { get; set; }
        public Nullable<double> BookingRooms_Services_Quantity { get; set; }
        public Nullable<decimal> BookingRooms_Services_CostRef_Services { get; set; }
        public string BookingRooms_CodeRoom { get; set; }
        public Nullable<int> BookingRooms_Services_IndexSubPayment { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_InvoiceDate { get; set; }
        public string BookingRooms_Services_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_AcceptDate { get; set; }
    }
}
