//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QueryDataPayment
    {
        public int BookingRs_ID { get; set; }
        public int BookingRooms_ID { get; set; }
        public Nullable<int> BookingHalls_ID { get; set; }
        public Nullable<int> BookingHs_ID { get; set; }
        public Nullable<int> BookingRooms_Services_Status { get; set; }
        public Nullable<int> BookingHalls_Services_Status { get; set; }
        public Nullable<int> BookingRooms_Services_IDService { get; set; }
        public string Services_Name_Room { get; set; }
        public Nullable<int> BookingHalls_Services_IDService { get; set; }
        public string Services_Name_Hall { get; set; }
        public Nullable<System.DateTime> BookingHs_CreatedDate { get; set; }
        public Nullable<System.DateTime> BookingRs_CreatedDate { get; set; }
        public Nullable<int> Services_IDServiceGroups_Room { get; set; }
        public Nullable<int> Services_Type_Room { get; set; }
        public Nullable<int> Services_Type_Hall { get; set; }
        public Nullable<int> Services_IDServiceGroups_Hall { get; set; }
        public string Rooms_Sku { get; set; }
        public Nullable<int> Rooms_IDLang { get; set; }
        public Nullable<int> Halls_IDLang { get; set; }
        public string Halls_Sku { get; set; }
        public Nullable<decimal> BookingRooms_Services_Cost { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_Date { get; set; }
        public Nullable<double> BookingRooms_Services_PercentTax { get; set; }
        public Nullable<double> BookingRooms_Services_Quantity { get; set; }
        public Nullable<int> BookingRooms_Services_IndexSubPayment { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_InvoiceDate { get; set; }
        public string BookingRooms_Services_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_AcceptDate { get; set; }
        public Nullable<bool> BookingRooms_Services_Disable { get; set; }
        public Nullable<System.DateTime> BookingHalls_Services_InvoiceDate { get; set; }
        public Nullable<System.DateTime> BookingHalls_Services_AcceptDate { get; set; }
        public string BookingHalls_Services_InvoiceNumber { get; set; }
        public Nullable<int> BookingHalls_Services_IndexSubPayment { get; set; }
        public Nullable<double> BookingHalls_Services_Quantity { get; set; }
        public Nullable<double> BookingHalls_Services_PercentTax { get; set; }
        public Nullable<System.DateTime> BookingHalls_Services_Date { get; set; }
        public Nullable<decimal> BookingHalls_Services_Cost { get; set; }
        public Nullable<bool> BookingHalls_Services_Disable { get; set; }
        public Nullable<int> BookingHalls_Services_Type { get; set; }
        public Nullable<int> BookingHalls_Services_ID { get; set; }
        public Nullable<System.DateTime> BookingRooms_AcceptDate { get; set; }
        public string BookingRooms_InvoiceNumber { get; set; }
        public Nullable<int> BookingRooms_Services_Type { get; set; }
        public Nullable<System.DateTime> BookingRooms_InvoiceDate { get; set; }
        public Nullable<int> BookingHalls_Status { get; set; }
        public Nullable<System.DateTime> BookingHalls_InvoiceDate { get; set; }
        public string BookingHalls_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingHalls_AcceptDate { get; set; }
        public Nullable<int> BookingHalls_IndexSubPayment { get; set; }
        public int BookingRs_IDCustomer { get; set; }
        public string BookingRs_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingRs_InvoiceDate { get; set; }
        public Nullable<System.DateTime> BookingRs_AcceptDate { get; set; }
        public System.DateTime BookingRooms_CheckInActual { get; set; }
        public System.DateTime BookingRooms_CheckOutActual { get; set; }
        public Nullable<int> BookingRooms_Status { get; set; }
        public Nullable<int> BookingRooms_IndexSubPayment { get; set; }
        public string BookingHs_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingHs_InvoiceDate { get; set; }
        public Nullable<System.DateTime> BookingHs_AcceptDate { get; set; }
        public Nullable<int> BookingRs_Status { get; set; }
        public Nullable<int> BookingHs_Status { get; set; }
        public Nullable<int> BookingRs_PayMenthod { get; set; }
        public Nullable<System.DateTime> BookingHalls_Date { get; set; }
        public Nullable<System.DateTime> BookingHalls_LunarDate { get; set; }
    }
}
