//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Support2_DataPayment
    {
        public int BookingHs_ID { get; set; }
        public Nullable<System.DateTime> BookingHs_CreatedDate { get; set; }
        public Nullable<int> BookingHs_CustomerType { get; set; }
        public Nullable<int> BookingHs_BookingType { get; set; }
        public Nullable<int> BookingHs_PayMenthod { get; set; }
        public Nullable<int> BookingHs_StatusPay { get; set; }
        public Nullable<decimal> BookingHs_BookingMoney { get; set; }
        public Nullable<int> BookingHs_Status { get; set; }
        public Nullable<int> BookingHs_Type { get; set; }
        public Nullable<bool> BookingHs_Disable { get; set; }
        public Nullable<int> BookingHs_Level { get; set; }
        public string BookingHs_Subject { get; set; }
        public int BookingHs_IDCustomer { get; set; }
        public int BookingHs_IDCustomerGroup { get; set; }
        public Nullable<System.DateTime> BookingHs_DatePay { get; set; }
        public string BookingHs_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingHs_InvoiceDate { get; set; }
        public Nullable<System.DateTime> BookingHs_AcceptDate { get; set; }
        public int BookingHalls_ID { get; set; }
        public string BookingHalls_CodeHall { get; set; }
        public Nullable<decimal> BookingHalls_Cost { get; set; }
        public Nullable<double> BookingHalls_PercentTax { get; set; }
        public Nullable<System.DateTime> BookingHalls_Date { get; set; }
        public Nullable<System.DateTime> BookingHalls_LunarDate { get; set; }
        public Nullable<int> BookingHalls_BookingStatus { get; set; }
        public Nullable<System.TimeSpan> BookingHalls_StartTime { get; set; }
        public Nullable<System.TimeSpan> BookingHalls_EndTime { get; set; }
        public Nullable<int> BookingHalls_IndexSubPayment { get; set; }
        public Nullable<System.DateTime> BookingHalls_InvoiceDate { get; set; }
        public string BookingHalls_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingHalls_AcceptDate { get; set; }
        public Nullable<int> BookingHalls_Status { get; set; }
        public Nullable<int> BookingHalls_Services_ID { get; set; }
        public Nullable<int> BookingHalls_Services_Type { get; set; }
        public Nullable<int> BookingHalls_Services_Status { get; set; }
        public Nullable<bool> BookingHalls_Services_Disable { get; set; }
        public Nullable<int> BookingHalls_Services_IDService { get; set; }
        public Nullable<decimal> BookingHalls_Services_Cost { get; set; }
        public Nullable<System.DateTime> BookingHalls_Services_Date { get; set; }
        public Nullable<double> BookingHalls_Services_PercentTax { get; set; }
        public Nullable<double> BookingHalls_Services_Quantity { get; set; }
        public Nullable<int> BookingHalls_Services_IndexSubPayment { get; set; }
        public Nullable<System.DateTime> BookingHalls_Services_AcceptDate { get; set; }
        public string BookingHalls_Services_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingHalls_Services_InvoiceDate { get; set; }
        public string Services_Name_Hall { get; set; }
        public Nullable<int> Services_Status_Hall { get; set; }
        public Nullable<int> Services_Type_Hall { get; set; }
        public Nullable<int> Services_IDServiceGroups_Hall { get; set; }
        public string Halls_Sku { get; set; }
        public Nullable<int> Halls_IDLang { get; set; }
    }
}
