//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Support1_DataPayment
    {
        public int BookingRs_ID { get; set; }
        public int BookingRooms_ID { get; set; }
        public Nullable<int> BookingRooms_Services_IDService { get; set; }
        public Nullable<System.DateTime> BookingRs_CreatedDate { get; set; }
        public Nullable<int> BookingRs_CustomerType { get; set; }
        public Nullable<int> BookingRs_BookingType { get; set; }
        public int BookingRs_IDCustomer { get; set; }
        public int BookingRs_IDSystemUser { get; set; }
        public Nullable<int> BookingRs_PayMenthod { get; set; }
        public Nullable<int> BookingRs_StatusPay { get; set; }
        public Nullable<decimal> BookingRs_BookingMoney { get; set; }
        public Nullable<int> BookingRs_Status { get; set; }
        public Nullable<int> BookingRs_Type { get; set; }
        public Nullable<bool> BookingRs_Disable { get; set; }
        public int BookingRs_Level { get; set; }
        public string BookingRs_Subject { get; set; }
        public System.DateTime BookingRs_DatePay { get; set; }
        public System.DateTime BookingRs_DateEdit { get; set; }
        public int BookingRs_IDCustomerGroup { get; set; }
        public string BookingRs_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingRs_InvoiceDate { get; set; }
        public Nullable<System.DateTime> BookingRs_AcceptDate { get; set; }
        public string BookingRooms_CodeRoom { get; set; }
        public Nullable<decimal> BookingRooms_Cost { get; set; }
        public Nullable<double> BookingRooms_PercentTax { get; set; }
        public System.DateTime BookingRooms_CheckInPlan { get; set; }
        public System.DateTime BookingRooms_CheckInActual { get; set; }
        public System.DateTime BookingRooms_CheckOutPlan { get; set; }
        public System.DateTime BookingRooms_CheckOutActual { get; set; }
        public Nullable<int> BookingRooms_BookingStatus { get; set; }
        public Nullable<int> BookingRooms_Status { get; set; }
        public Nullable<double> BookingRooms_CostPendingRoom { get; set; }
        public Nullable<decimal> BookingRooms_TimeInUse { get; set; }
        public Nullable<int> BookingRooms_Type { get; set; }
        public Nullable<bool> BookingRooms_Disable { get; set; }
        public Nullable<int> BookingRooms_IndexSubPayment { get; set; }
        public string BookingRooms_PriceType { get; set; }
        public Nullable<decimal> BookingRooms_AddTimeStart { get; set; }
        public Nullable<decimal> BookingRooms_AddTimeEnd { get; set; }
        public Nullable<System.DateTime> BookingRooms_AcceptDate { get; set; }
        public string BookingRooms_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingRooms_InvoiceDate { get; set; }
        public Nullable<int> BookingRooms_Services_Type { get; set; }
        public Nullable<int> BookingRooms_Services_Status { get; set; }
        public Nullable<bool> BookingRooms_Services_Disable { get; set; }
        public Nullable<decimal> BookingRooms_Services_Cost { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_Date { get; set; }
        public Nullable<double> BookingRooms_Services_PercentTax { get; set; }
        public Nullable<double> BookingRooms_Services_Quantity { get; set; }
        public Nullable<int> BookingRooms_Services_IndexSubPayment { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_InvoiceDate { get; set; }
        public string BookingRooms_Services_InvoiceNumber { get; set; }
        public Nullable<System.DateTime> BookingRooms_Services_AcceptDate { get; set; }
        public string Services_Name_Room { get; set; }
        public Nullable<int> Services_IDServiceGroups_Room { get; set; }
        public Nullable<int> Services_Type_Room { get; set; }
        public Nullable<int> Rooms_IDLang { get; set; }
        public string Rooms_Sku { get; set; }
    }
}
